# Generated by Django 5.2 on 2025-06-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0005_inventory"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
    ]
